
import {
  BarChart3,
  ClipboardList,
  Coffee,
  Globe,
  Home,
  MessageSquare,
  PanelLeft,
  Award,
  Calendar,
  Store,
  Settings,
  UserCircle,
  CreditCard,
  Ticket,
  Users,
  FileText
} from "lucide-react";
import { NavItem } from "@/types/navigation";

export const navigationItems: NavItem[] = [
  {
    title: "Dashboard",
    name: "Dashboard",
    icon: Home,
    href: "/dashboard",
    roles: ["superadmin", "franchise_owner", "franchise_manager"],
  },
  {
    title: "Reports & Analytics",
    name: "Reports & Analytics",
    icon: FileText,
    href: "/analytics",
    roles: ["superadmin", "franchise_owner", "franchise_manager"],
  },
  {
    title: "Franchises",
    name: "Franchises",
    icon: Store,
    href: "/franchises",
    roles: ["superadmin"],
  },
  {
    title: "Operations",
    name: "Operations",
    icon: PanelLeft,
    href: "/operations",
    roles: ["franchise_manager"],
  },
  {
    title: "Schedule",
    name: "Schedule",
    icon: Calendar,
    href: "/schedule",
    roles: ["superadmin", "franchise_owner", "franchise_manager"],
  },
  {
    title: "Sessions",
    name: "Sessions",
    icon: ClipboardList,
    href: "/sessions",
    roles: ["superadmin", "franchise_owner", "franchise_manager"],
  },
  {
    title: "Dining",
    name: "Dining",
    icon: Coffee,
    href: "/dining",
    category: "dining",
    roles: ["superadmin", "franchise_owner", "franchise_manager"],
  },
  {
    title: "Staff",
    name: "Staff",
    icon: Users,
    href: "/staff",
    roles: ["superadmin", "franchise_owner", "franchise_manager"],
  },
  {
    title: "Bookings",
    name: "Bookings",
    icon: Calendar,
    href: "/bookings",
    roles: ["superadmin", "franchise_owner", "franchise_manager"],
  },
  {
    title: "Payments",
    name: "Payments",
    icon: CreditCard,
    href: "/payments",
    roles: ["superadmin", "franchise_owner", "franchise_manager"],
  },
  {
    title: "Offers",
    name: "Offers",
    icon: Ticket,
    href: "/offers",
    roles: ["superadmin", "franchise_owner", "franchise_manager"],
  },
  {
    title: "Guests",
    name: "Guests",
    icon: UserCircle,
    href: "/guests",
    roles: ["superadmin", "franchise_owner", "franchise_manager"],
  },
  {
    title: "Lead Management",
    name: "Lead Management",
    icon: MessageSquare,
    href: "/lead-management",
    roles: ["superadmin", "franchise_owner", "franchise_manager"],
  },
  {
    title: "Settings & Security",
    name: "Settings",
    icon: Settings,
    href: "/settings",
    roles: ["superadmin", "franchise_owner"],
  },
];
