
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase';

const SUPABASE_URL = "https://vjwxmgaoqsfdyynqwynz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqd3htZ2FvcXNmZHl5bnF3eW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTU3MTAsImV4cCI6MjA1OTc3MTcxMH0.fwds4kW8m8WJSsPSyS5Xmx4VFH9R_SDqCyZQAFwqFuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
